version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: blulyk-calorieai_web_1
      APP_PORT: 3000
      PROXY_AUTH_ADD: "false"

  web:
    image: ghcr.io/blulyk/calorieai:3e5cfc3bd46264d094c01303b9c509b9f75e6adc
    container_name: blulyk-calorieai_web_1
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - "${APP_DATA_DIR}/data:/data"
      - "${APP_DATA_DIR}/uploads:/app/public/uploads"
    environment:
      NODE_ENV: "production"
      DB_PATH: "/data"
      JWT_SECRET: "${APP_SEED}"
    ports:
      - "${APP_PORT}:3000"
