version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: blulyk-calorieai_web_1
      APP_PORT: 3000
      PROXY_AUTH_ADD: "false"

  web:
    image: ghcr.io/blulyk/calorieai:6be6b380050dea33c083b3171c1c0d49eb3614b2
    container_name: blulyk-calorieai_web_1
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - "${APP_DATA_DIR}/data:/data"
      - "${APP_DATA_DIR}/uploads:/app/public/uploads"
    environment:
      NODE_ENV: "production"
      DB_PATH: "/data"
      JWT_SECRET: "${APP_SEED}"
    ports:
      - "${APP_PORT}:3000"
