version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: blulyk-coolify_coolify_1
      APP_PORT: 8080

  coolify:
    image: docker.io/coollabsio/coolify:4.1.2
    container_name: blulyk-coolify_coolify_1
    restart: unless-stopped
    working_dir: /var/www/html
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      APP_ENV: production
      PHP_MEMORY_LIMIT: 256M
      PHP_FPM_PM_CONTROL: dynamic
      PHP_FPM_PM_START_SERVERS: 1
      PHP_FPM_PM_MIN_SPARE_SERVERS: 1
      PHP_FPM_PM_MAX_SPARE_SERVERS: 10
      TZ: Europe/Madrid
    env_file:
      - "${APP_DATA_DIR}/data/source/.env"
    volumes:
      - "${APP_DATA_DIR}/data/source/.env:/var/www/html/.env:ro"
      - "${APP_DATA_DIR}/data/ssh:/var/www/html/storage/app/ssh"
      - "${APP_DATA_DIR}/data/applications:/var/www/html/storage/app/applications"
      - "${APP_DATA_DIR}/data/databases:/var/www/html/storage/app/databases"
      - "${APP_DATA_DIR}/data/services:/var/www/html/storage/app/services"
      - "${APP_DATA_DIR}/data/backups:/var/www/html/storage/app/backups"
    healthcheck:
      test: "curl --fail http://127.0.0.1:8080/api/health || exit 1"
      interval: 5s
      retries: 10
      timeout: 2s
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      soketi:
        condition: service_healthy
    networks:
      - coolify

  postgres:
    image: postgres:15-alpine
    container_name: blulyk-coolify_postgres_1
    restart: unless-stopped
    env_file:
      - "${APP_DATA_DIR}/data/source/.env"
    environment:
      POSTGRES_USER: coolify
      POSTGRES_DB: coolify
    volumes:
      - "${APP_DATA_DIR}/data/postgres:/var/lib/postgresql/data"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      retries: 10
      timeout: 2s
    networks:
      - coolify

  redis:
    image: redis:7-alpine
    container_name: blulyk-coolify_redis_1
    restart: unless-stopped
    env_file:
      - "${APP_DATA_DIR}/data/source/.env"
    command: sh -c 'redis-server --save 20 1 --loglevel warning --requirepass "$$REDIS_PASSWORD"'
    volumes:
      - "${APP_DATA_DIR}/data/redis:/data"
    healthcheck:
      test: ["CMD-SHELL", "redis-cli -a \"$${REDIS_PASSWORD}\" ping || exit 1"]
      interval: 5s
      retries: 10
      timeout: 2s
    networks:
      - coolify

  soketi:
    image: docker.io/coollabsio/coolify-realtime:1.0.16
    container_name: blulyk-coolify_soketi_1
    restart: unless-stopped
    env_file:
      - "${APP_DATA_DIR}/data/source/.env"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      APP_NAME: Coolify
      SOKETI_DEBUG: "false"
      SOKETI_HOST: "0.0.0.0"
    volumes:
      - "${APP_DATA_DIR}/data/ssh:/var/www/html/storage/app/ssh"
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1:6001/ready && wget -qO- http://127.0.0.1:6002/ready || exit 1"]
      interval: 5s
      retries: 10
      timeout: 2s
    networks:
      - coolify

networks:
  coolify:
    name: blulyk-coolify
    driver: bridge
