use_default_settings: true

server:
  secret_key: "__SEARXNG_SECRET__"

search:
  formats:
    - html
    - json

default_doi_resolver: "https://doi.org/"
doi_resolvers:
  doi.org: "https://doi.org/"
