version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: blulyk-obsidian-livesync_couchdb_1
      APP_PORT: 5984

  couchdb:
    image: couchdb:3
    init: true
    restart: on-failure
    stop_grace_period: 30s
    ports:
      - "5985:5984"
    environment:
      COUCHDB_USER: "admin"
      COUCHDB_PASSWORD: "livesync"
    volumes:
      - "${APP_DATA_DIR}/data:/opt/couchdb/data"
      - "${APP_DATA_DIR}/config:/opt/couchdb/etc/local.d"
    container_name: blulyk-obsidian-livesync_couchdb_1
